name: Run test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and run nargo
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Install dependencies
        run: npm install

      - name: Install playwright deps
        run: |
          npx playwright install
          npx playwright install-deps

      - name: Run tests
        run: npm run test:browser
