name: Run test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
